/**
@Name            : EventCheckInConfirmationControllerTest
@Description     : Test class for 'EventCheckInConfirmationController' Class 
**/
@isTest
public class EventCheckInConfirmationControllerTest{
    @isTest
    public static void unitTest(){
    
    EventCheckInConfirmationController controller= new EventCheckInConfirmationController();
    controller.redirectToEventCheckIn();
    }
    
 }